version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatflow-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - chatflow-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatflow-frontend
    ports:
      - "8080:80"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - chatflow-network

  redis:
    image: redis:7-alpine
    container_name: chatflow-redis
    ports:
      - "6379:6379"
    networks:
      - chatflow-network
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chatflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - chatflow-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  chatflow-network:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data: