version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: chatflow-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - frontend
    networks:
      - chatflow-network

  backend1:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatflow-backend-1
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - chatflow-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  backend2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chatflow-backend-2
    env_file:
      - ./backend/.env
    depends_on:
      - redis
      - rabbitmq
    networks:
      - chatflow-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: chatflow-frontend
    networks:
      - chatflow-network

  redis:
    image: redis:7-alpine
    container_name: chatflow-redis
    ports:
      - "6379:6379"
    networks:
      - chatflow-network
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: chatflow-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - chatflow-network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

networks:
  chatflow-network:
    driver: bridge

volumes:
  redis_data:
  rabbitmq_data: